change: quit auto npm init

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,18 +1,36 @@
 #!/bin/bash
 
-scriptName="tmp_conifg"
+trap 'echo "Download failed :<"; exit 1' 1 2 3 15
 
-function clean() {
-  echo "Download failed :<"
-  if [ -f $scriptName ]; then
-    rm -f $scriptName
-  fi
+files=(.eslintrc .editorconfig)
+
+URL="https://raw.githubusercontent.com/goods-inc/config-files/master"
+logo='
+    ___   ________           ________   ________   ________    ________  ___   ________
+   |\  \ |\   ____\         |\   ____\ |\   __  \ |\   ___  \ |\  _____\|\  \ |\   ____\
+   \ \  \\ \  \___|_        \ \  \___| \ \  \|\  \\ \  \\ \  \\ \  \__/ \ \  \\ \  \___|
+ __ \ \  \\ \_____  \        \ \  \     \ \  \\\  \\ \  \\ \  \\ \   __\ \ \  \\ \  \  ___
+|\  \\_\  \\|____|\  \        \ \  \____ \ \  \\\  \\ \  \\ \  \\ \  \_|  \ \  \\ \  \|\  \
+\ \________\ ____\_\  \        \ \_______\\ \_______\\ \__\\ \__\\ \__\    \ \__\\ \_______\
+ \|________||\_________\        \|_______| \|_______| \|__| \|__| \|__|     \|__| \|_______|
+            \|_________|
+
+'
+
+if [ ! -f "package.json" ]; then
+  echo "There is no package.json"
+  echo "Maybe you need to run 'npm init'"
   exit 1
-}
+fi
 
-trap 'clean' 1 2 3 15
+npm install --save-dev eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y eslint
 
+echo "Start downloading ${files[@]} ..."
+for file in ${files[@]}
+do
+  curl -sO "$URL/$file"
+  echo "Download $file"
+done
 
-curl "https://raw.githubusercontent.com/goods-inc/config-files/master/init" > $scriptName
-
-bash $scriptName
+echo "Download fininshed!!"
+echo "$logo"
